SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES S WHERE S.NAME IN ('Python'))
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES S WHERE S.NAME IN ('C#'))
ORDER BY ID ASC;